version: '3'
services:
  mongo-database:
    build: "../mongo-service"
    hostname: mongodb-server
    ports:
      - "27017:27017"
    networks:
      - vsu-microservices
    container_name: "mongodb-server"

  flats-microservice:
    build: "../flats-microservice/."
    hostname: "flats-server"
    container_name: "flats-server"
    environment:
      - DB_SERVERS=mongodb-server:27017
    networks:
      - vsu-microservices
    depends_on:
      - "mongo-database"
    ports:
      - "3000:3000"

networks:
  vsu-microservices:
    driver: bridge